import type {
  AnalysisJob,
  Evidence,
  Finding,
  Observation,
  Report,
  Session,
  User,
} from "@/types";

export const users: User[] = [
  { id: "u1", name: "Ana Torres", email: "ana@infrainspect.ai", role: "admin" },
  { id: "u2", name: "Diego Salas", email: "diego@infrainspect.ai", role: "inspector" },
  { id: "u3", name: "Marta Quiroz", email: "marta@infrainspect.ai", role: "engineer" },
  { id: "u4", name: "Leo Vega", email: "leo@infrainspect.ai", role: "inspector" },
  { id: "u5", name: "Sofía Rivas", email: "sofia@infrainspect.ai", role: "viewer" },
];

export const currentUser: User = users[0];

export const sessions: Session[] = [
  {
    id: "s1",
    code: "INS-2026-0142",
    title: "Línea de Alta Tensión — Tramo Norte",
    status: "Processing",
    infrastructure: {
      id: "i1",
      name: "LAT-500kV Andes Norte",
      type: "Power Line",
      location: "Cajamarca, Perú",
      coordinates: { lat: -7.1638, lng: -78.5003 },
      assetCode: "LAT-N-500",
      operator: "Red Eléctrica Andina",
      commissionedYear: 2014,
    },
    createdAt: "2026-05-28T09:00:00Z",
    updatedAt: "2026-06-04T11:32:00Z",
    leadInspectorId: "u2",
    teamIds: ["u2", "u3"],
    evidenceCount: 48,
    findingsCount: 17,
    criticalFindings: 3,
    progress: 62,
    weather: "Despejado, 14°C, viento 12 km/h",
    notes: "Inspección programada por reporte de descargas atmosféricas.",
  },
  {
    id: "s2",
    code: "INS-2026-0141",
    title: "Parque Eólico Sur — Turbinas T12-T18",
    status: "Capturing",
    infrastructure: {
      id: "i2",
      name: "PE Marcona Sur",
      type: "Wind Turbine",
      location: "Ica, Perú",
      coordinates: { lat: -15.34, lng: -75.12 },
      assetCode: "PE-MAR-S",
      operator: "EnerWind Pacífico",
      commissionedYear: 2019,
    },
    createdAt: "2026-06-02T07:30:00Z",
    updatedAt: "2026-06-04T10:14:00Z",
    leadInspectorId: "u4",
    teamIds: ["u4"],
    evidenceCount: 22,
    findingsCount: 5,
    criticalFindings: 1,
    progress: 35,
  },
  {
    id: "s3",
    code: "INS-2026-0140",
    title: "Puente Atirantado Río Rímac",
    status: "Review",
    infrastructure: {
      id: "i3",
      name: "Puente Rímac-04",
      type: "Bridge",
      location: "Lima, Perú",
      coordinates: { lat: -12.027, lng: -77.043 },
      assetCode: "BR-RIM-04",
      operator: "MTC",
      commissionedYear: 2008,
    },
    createdAt: "2026-05-20T08:00:00Z",
    updatedAt: "2026-06-03T17:00:00Z",
    leadInspectorId: "u2",
    teamIds: ["u2", "u3", "u5"],
    evidenceCount: 134,
    findingsCount: 41,
    criticalFindings: 6,
    progress: 88,
  },
  {
    id: "s4",
    code: "INS-2026-0139",
    title: "Granja Solar — Sector C",
    status: "Completed",
    infrastructure: {
      id: "i4",
      name: "Solar Atacama C",
      type: "Solar Farm",
      location: "Arequipa, Perú",
      coordinates: { lat: -16.4, lng: -71.55 },
      assetCode: "SF-ATC-C",
      operator: "SolMax Energía",
      commissionedYear: 2021,
    },
    createdAt: "2026-05-10T08:00:00Z",
    updatedAt: "2026-05-22T16:00:00Z",
    completedAt: "2026-05-22T16:00:00Z",
    leadInspectorId: "u3",
    teamIds: ["u3", "u4"],
    evidenceCount: 312,
    findingsCount: 64,
    criticalFindings: 2,
    progress: 100,
  },
  {
    id: "s5",
    code: "INS-2026-0138",
    title: "Torre Telecom — Cerro El Mirador",
    status: "Draft",
    infrastructure: {
      id: "i5",
      name: "Torre TLC-Mirador",
      type: "Telecom Tower",
      location: "Cusco, Perú",
      coordinates: { lat: -13.52, lng: -71.97 },
      assetCode: "TT-MIR-01",
      operator: "AndinaCom",
      commissionedYear: 2016,
    },
    createdAt: "2026-06-04T13:00:00Z",
    updatedAt: "2026-06-04T13:00:00Z",
    scheduledFor: "2026-06-09T08:00:00Z",
    leadInspectorId: "u4",
    teamIds: ["u4"],
    evidenceCount: 0,
    findingsCount: 0,
    criticalFindings: 0,
    progress: 0,
  },
  {
    id: "s6",
    code: "INS-2026-0137",
    title: "Oleoducto Tramo 4B",
    status: "Completed",
    infrastructure: {
      id: "i6",
      name: "OL-Norte 4B",
      type: "Pipeline",
      location: "Loreto, Perú",
      coordinates: { lat: -3.74, lng: -73.25 },
      assetCode: "OL-N-4B",
      operator: "PetroAndes",
      commissionedYear: 2002,
    },
    createdAt: "2026-04-12T08:00:00Z",
    updatedAt: "2026-04-30T18:00:00Z",
    completedAt: "2026-04-30T18:00:00Z",
    leadInspectorId: "u2",
    teamIds: ["u2", "u3"],
    evidenceCount: 198,
    findingsCount: 33,
    criticalFindings: 5,
    progress: 100,
  },
];

export const evidence: Evidence[] = [
  {
    id: "e1",
    sessionId: "s1",
    type: "rtmp",
    filename: "stream-cam-norte.live",
    mimeType: "video/rtmp",
    sizeBytes: 0,
    uploadedAt: "2026-06-04T10:00:00Z",
    uploadedBy: "u2",
    status: "processing",
    rtmpUrl: "rtmp://stream.infrainspect.ai/live/cam-norte",
  },
  {
    id: "e2",
    sessionId: "s1",
    type: "image",
    filename: "torre-12-vano-N.jpg",
    mimeType: "image/jpeg",
    sizeBytes: 4_200_000,
    uploadedAt: "2026-06-04T09:42:00Z",
    uploadedBy: "u2",
    status: "analyzed",
    capturedAt: "2026-06-04T09:30:00Z",
    geo: { lat: -7.163, lng: -78.5, alt: 2840 },
    tags: ["aislador", "vano-norte"],
  },
  {
    id: "e3",
    sessionId: "s1",
    type: "video",
    filename: "drone-pass-T12.mp4",
    mimeType: "video/mp4",
    sizeBytes: 184_000_000,
    uploadedAt: "2026-06-04T08:55:00Z",
    uploadedBy: "u2",
    status: "queued",
    durationSec: 412,
  },
  {
    id: "e4",
    sessionId: "s1",
    type: "pdf",
    filename: "informe-previo-2025.pdf",
    mimeType: "application/pdf",
    sizeBytes: 2_100_000,
    uploadedAt: "2026-05-28T09:10:00Z",
    uploadedBy: "u3",
    status: "uploaded",
  },
  {
    id: "e5",
    sessionId: "s2",
    type: "image",
    filename: "T15-pala-A.png",
    mimeType: "image/png",
    sizeBytes: 6_800_000,
    uploadedAt: "2026-06-04T09:10:00Z",
    uploadedBy: "u4",
    status: "analyzed",
  },
  {
    id: "e6",
    sessionId: "s3",
    type: "video",
    filename: "tirante-norte-04.mov",
    mimeType: "video/quicktime",
    sizeBytes: 240_000_000,
    uploadedAt: "2026-05-30T14:00:00Z",
    uploadedBy: "u3",
    status: "analyzed",
    durationSec: 612,
  },
];

export const analysisJobs: AnalysisJob[] = [
  {
    id: "j1",
    sessionId: "s1",
    evidenceId: "e1",
    model: "YOLOv8-Infra-v3",
    status: "running",
    progress: 71,
    startedAt: "2026-06-04T10:01:00Z",
    findingsProduced: 4,
  },
  {
    id: "j2",
    sessionId: "s1",
    evidenceId: "e3",
    model: "YOLOv8-Infra-v3",
    status: "queued",
    progress: 0,
    findingsProduced: 0,
  },
  {
    id: "j3",
    sessionId: "s1",
    evidenceId: "e2",
    model: "YOLOv8-Infra-v3",
    status: "succeeded",
    progress: 100,
    startedAt: "2026-06-04T09:43:00Z",
    finishedAt: "2026-06-04T09:44:12Z",
    inferenceTimeMs: 72_300,
    findingsProduced: 6,
  },
  {
    id: "j4",
    sessionId: "s2",
    evidenceId: "e5",
    model: "YOLOv8-Turbine",
    status: "succeeded",
    progress: 100,
    findingsProduced: 3,
    inferenceTimeMs: 48_000,
  },
  {
    id: "j5",
    sessionId: "s3",
    evidenceId: "e6",
    model: "YOLOv8-Struct",
    status: "failed",
    progress: 32,
    findingsProduced: 0,
    error: "GPU OOM al frame 4218",
  },
];

export const findings: Finding[] = [
  {
    id: "f1",
    sessionId: "s1",
    evidenceId: "e2",
    jobId: "j3",
    category: "Corrosión severa",
    severity: "critical",
    confidence: 0.94,
    status: "pending",
    description: "Corrosión avanzada en grapa de suspensión, pérdida >40% de sección.",
    detectedAt: "2026-06-04T09:44:00Z",
    bbox: { x: 0.42, y: 0.31, w: 0.18, h: 0.22 },
    geo: { lat: -7.163, lng: -78.5 },
    recommendation: "Reemplazo inmediato. Coordinar corte programado en 7 días.",
  },
  {
    id: "f2",
    sessionId: "s1",
    evidenceId: "e2",
    jobId: "j3",
    category: "Aislador roto",
    severity: "high",
    confidence: 0.88,
    status: "validated",
    description: "Aislador de porcelana fracturado en cadena 3.",
    detectedAt: "2026-06-04T09:44:00Z",
    validatedBy: "u3",
    validatedAt: "2026-06-04T11:02:00Z",
    recommendation: "Programar reemplazo en próxima ventana de mantenimiento.",
  },
  {
    id: "f3",
    sessionId: "s1",
    evidenceId: "e2",
    category: "Vegetación invasiva",
    severity: "medium",
    confidence: 0.81,
    status: "needs_review",
    description: "Crecimiento de vegetación dentro de la franja de servidumbre.",
    detectedAt: "2026-06-04T09:44:00Z",
    recommendation: "Poda en 30 días.",
  },
  {
    id: "f4",
    sessionId: "s2",
    evidenceId: "e5",
    category: "Erosión por borde de ataque",
    severity: "high",
    confidence: 0.79,
    status: "pending",
    description: "Delaminación visible en borde de ataque, pala A turbina T15.",
    detectedAt: "2026-06-04T09:12:00Z",
    recommendation: "Inspección táctil con técnico rappel.",
  },
  {
    id: "f5",
    sessionId: "s3",
    evidenceId: "e6",
    category: "Fisura en concreto",
    severity: "critical",
    confidence: 0.92,
    status: "validated",
    description: "Fisura longitudinal 1.8m en anclaje sur, ancho ~3mm.",
    detectedAt: "2026-05-30T14:30:00Z",
    validatedBy: "u3",
    validatedAt: "2026-05-31T09:00:00Z",
    recommendation: "Monitoreo continuo + intervención estructural.",
  },
  {
    id: "f6",
    sessionId: "s3",
    evidenceId: "e6",
    category: "Pintura deteriorada",
    severity: "low",
    confidence: 0.86,
    status: "validated",
    description: "Capa anticorrosiva degradada en pilón norte.",
    detectedAt: "2026-05-30T14:35:00Z",
    validatedBy: "u2",
    validatedAt: "2026-05-31T10:00:00Z",
  },
  {
    id: "f7",
    sessionId: "s4",
    evidenceId: "e5",
    category: "Hot-spot termográfico",
    severity: "high",
    confidence: 0.9,
    status: "validated",
    description: "Punto caliente en string 14, ΔT = 24°C.",
    detectedAt: "2026-05-21T15:00:00Z",
    validatedBy: "u3",
    validatedAt: "2026-05-22T09:00:00Z",
  },
  {
    id: "f8",
    sessionId: "s4",
    evidenceId: "e5",
    category: "Suciedad acumulada",
    severity: "info",
    confidence: 0.72,
    status: "rejected",
    description: "Polvo en módulos sector C-7.",
    detectedAt: "2026-05-21T15:10:00Z",
    validatedBy: "u4",
    validatedAt: "2026-05-22T10:00:00Z",
  },
];

export const observations: Observation[] = [
  {
    id: "o1",
    findingId: "f1",
    authorId: "u3",
    authorName: "Marta Quiroz",
    createdAt: "2026-06-04T10:50:00Z",
    comment: "Confirmado en zoom 4x — pérdida de sección visible.",
    action: "comment",
  },
  {
    id: "o2",
    findingId: "f2",
    authorId: "u3",
    authorName: "Marta Quiroz",
    createdAt: "2026-06-04T11:02:00Z",
    comment: "Validado. Coordinado con cuadrilla.",
    action: "validated",
  },
  {
    id: "o3",
    findingId: "f5",
    authorId: "u2",
    authorName: "Diego Salas",
    createdAt: "2026-05-31T09:00:00Z",
    comment: "Estructura comprometida, prioridad máxima.",
    action: "flagged",
  },
];

export const reports: Report[] = [
  {
    id: "r1",
    sessionId: "s4",
    code: "RPT-2026-0139",
    title: "Reporte técnico — Granja Solar Sector C",
    status: "signed",
    generatedAt: "2026-05-22T17:00:00Z",
    generatedBy: "u3",
    format: "pdf",
    pages: 42,
    fileUrl: "#",
    summary:
      "64 hallazgos, 2 críticos resueltos. Eficiencia recuperada 3.2%.",
  },
  {
    id: "r2",
    sessionId: "s6",
    code: "RPT-2026-0137",
    title: "Reporte técnico — Oleoducto Tramo 4B",
    status: "signed",
    generatedAt: "2026-04-30T19:00:00Z",
    generatedBy: "u2",
    format: "pdf",
    pages: 88,
    summary: "5 hallazgos críticos en soldaduras, intervención en curso.",
  },
  {
    id: "r3",
    sessionId: "s3",
    code: "RPT-2026-0140",
    title: "Reporte preliminar — Puente Rímac-04",
    status: "draft",
    generatedAt: "2026-06-03T18:00:00Z",
    generatedBy: "u3",
    format: "pdf",
    pages: 24,
    summary: "Hallazgo crítico estructural en anclaje sur.",
  },
];

export function getSession(id: string) {
  return sessions.find((s) => s.id === id);
}
export function getEvidenceBySession(id: string) {
  return evidence.filter((e) => e.sessionId === id);
}
export function getFindingsBySession(id: string) {
  return findings.filter((f) => f.sessionId === id);
}
export function getJobsBySession(id: string) {
  return analysisJobs.filter((j) => j.sessionId === id);
}
export function getReportsBySession(id: string) {
  return reports.filter((r) => r.sessionId === id);
}
export function getUser(id: string) {
  return users.find((u) => u.id === id);
}